//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders.DataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int Status { get; set; }
        public string Email { get; set; }
    }
}
