//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders.Web.Services.OrderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItem", Namespace="http://schemas.datacontract.org/2004/07/Orders.WcfService")]
    [System.SerializableAttribute()]
    public partial class OrderItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Orders.Web.Services.OrderServiceReference.OrderStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Orders.Web.Services.OrderServiceReference.OrderStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatus", Namespace="http://schemas.datacontract.org/2004/07/Orders.WcfService")]
    public enum OrderStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotSet = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InProgress = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Done = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderServiceReference.IOrderWcfService")]
    public interface IOrderWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderWcfService/Ping", ReplyAction="http://tempuri.org/IOrderWcfService/PingResponse")]
        string Ping(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderWcfService/Ping", ReplyAction="http://tempuri.org/IOrderWcfService/PingResponse")]
        System.Threading.Tasks.Task<string> PingAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderWcfService/GetOrders", ReplyAction="http://tempuri.org/IOrderWcfService/GetOrdersResponse")]
        System.Collections.Generic.List<Orders.Web.Services.OrderServiceReference.OrderItem> GetOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderWcfService/GetOrders", ReplyAction="http://tempuri.org/IOrderWcfService/GetOrdersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Orders.Web.Services.OrderServiceReference.OrderItem>> GetOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderWcfService/GetByKey", ReplyAction="http://tempuri.org/IOrderWcfService/GetByKeyResponse")]
        Orders.Web.Services.OrderServiceReference.OrderItem GetByKey(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderWcfService/GetByKey", ReplyAction="http://tempuri.org/IOrderWcfService/GetByKeyResponse")]
        System.Threading.Tasks.Task<Orders.Web.Services.OrderServiceReference.OrderItem> GetByKeyAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderWcfService/Add", ReplyAction="http://tempuri.org/IOrderWcfService/AddResponse")]
        Orders.Web.Services.OrderServiceReference.OrderItem Add(Orders.Web.Services.OrderServiceReference.OrderItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderWcfService/Add", ReplyAction="http://tempuri.org/IOrderWcfService/AddResponse")]
        System.Threading.Tasks.Task<Orders.Web.Services.OrderServiceReference.OrderItem> AddAsync(Orders.Web.Services.OrderServiceReference.OrderItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderWcfService/Delete", ReplyAction="http://tempuri.org/IOrderWcfService/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderWcfService/Delete", ReplyAction="http://tempuri.org/IOrderWcfService/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderWcfService/Update", ReplyAction="http://tempuri.org/IOrderWcfService/UpdateResponse")]
        void Update(Orders.Web.Services.OrderServiceReference.OrderItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderWcfService/Update", ReplyAction="http://tempuri.org/IOrderWcfService/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(Orders.Web.Services.OrderServiceReference.OrderItem item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderWcfServiceChannel : Orders.Web.Services.OrderServiceReference.IOrderWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderWcfServiceClient : System.ServiceModel.ClientBase<Orders.Web.Services.OrderServiceReference.IOrderWcfService>, Orders.Web.Services.OrderServiceReference.IOrderWcfService {
        
        public OrderWcfServiceClient() {
        }
        
        public OrderWcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderWcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderWcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderWcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Ping(string str) {
            return base.Channel.Ping(str);
        }
        
        public System.Threading.Tasks.Task<string> PingAsync(string str) {
            return base.Channel.PingAsync(str);
        }
        
        public System.Collections.Generic.List<Orders.Web.Services.OrderServiceReference.OrderItem> GetOrders() {
            return base.Channel.GetOrders();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Orders.Web.Services.OrderServiceReference.OrderItem>> GetOrdersAsync() {
            return base.Channel.GetOrdersAsync();
        }
        
        public Orders.Web.Services.OrderServiceReference.OrderItem GetByKey(int id) {
            return base.Channel.GetByKey(id);
        }
        
        public System.Threading.Tasks.Task<Orders.Web.Services.OrderServiceReference.OrderItem> GetByKeyAsync(int id) {
            return base.Channel.GetByKeyAsync(id);
        }
        
        public Orders.Web.Services.OrderServiceReference.OrderItem Add(Orders.Web.Services.OrderServiceReference.OrderItem item) {
            return base.Channel.Add(item);
        }
        
        public System.Threading.Tasks.Task<Orders.Web.Services.OrderServiceReference.OrderItem> AddAsync(Orders.Web.Services.OrderServiceReference.OrderItem item) {
            return base.Channel.AddAsync(item);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public void Update(Orders.Web.Services.OrderServiceReference.OrderItem item) {
            base.Channel.Update(item);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(Orders.Web.Services.OrderServiceReference.OrderItem item) {
            return base.Channel.UpdateAsync(item);
        }
    }
}
